---
- name: install webserver
  hosts: all
  become: true
  tasks:
    - yum:
        name: httpd
        state: latest
    - service:
        name: httpd
        state: started
        enabled: true
